[package]
name = "reto-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
image.workspace = true
rayon.workspace = true
serde.workspace = true
num-traits.workspace = true
ndarray.workspace = true
ort.workspace = true
ureq.workspace = true
kstring.workspace = true
sha2.workspace = true
color_quant.workspace = true
crossbeam-channel.workspace = true
libc.workspace = true
